### ISSUE TITLE
copying rebuild errors to the clipboard is not possible

### ISSUE THREAD

**Issue by despairblue** [atom/incompatible-packages#10]
That makes it hard to report them.

![screen shot 2015-10-30 at 14 13 04](https://cloud.githubusercontent.com/assets/927609/10846503/7679bad4-7f10-11e5-8b2c-86b75f3da470.png)

Copying them from the chrome dev tools works.

/ref https://github.com/atom/atom/issues/9351#issuecomment-153214844

**Comment by 50Wliu** [comment]
Should be fixed by atom/atom#9796.
