### ISSUE TITLE
Status bar icon too subtle

### ISSUE THREAD

**Issue by pfitzseb** [atom/incompatible-packages#23]
While the status bar icon is definitely nice to have, it's also too subtle for what it does: indicate that a package has been disabled entirely. We've gotten loads of user reports in the last couple of days (since the last Atom release), because no one could figure out that a package was disabled or what to do about it.

Just having a notification pop up would be much better imho -- if everyone agrees with that I'd be happy to open a PR :)

cc @Arcanemagus who pointed me here from slack

**Comment by lee-dohm** [comment]
Thanks for the feedback!

We haven't had any complaints about the way that we surface this information in the past and typically this only hits developers who are more in tune with new icons popping up in their status bar. We tend to avoid bringing up notifications unless they require immediate action, so our bar for showing a notification is pretty high.

Given all of that, we don't have any plans to make this change and won't be accepting a PR for the functionality.

Thanks again for your passion and interest :grinning:

**Comment by pfitzseb** [comment]
Fair enough, I guess, but I can't agree with this:
> typically this only hits developers who are more in tune with new icons popping up in their status bar

We got numerous reports from users that our package broke when they installed an Atom update, which was based on a different Electorn version and therefore required rebuilding. It's not super easy to work around this from our side since the package is not loaded *at all* and we would need to use a different pacakge as a kind of supervisor.

> We tend to avoid bringing up notifications unless they require immediate action

It does require immediate action if you want to continue using the package that just got disabled 😄 And even if you go to the package manager it won't be obvious what happened -- the package in question will just be missing the `Settings` button but will *not* be disabled or inform you about what happened.

Anyways, thanks for the answer :)
